%YAML:1.0

#--------------------------------------------------------------------------------------------
# Camera Parameters. Adjust them!
#--------------------------------------------------------------------------------------------
image_topic: "/usb_cam/image_raw"

CameraMat: !!opencv-matrix
  rows: 3
  cols: 3
  dt: d
  data: [1139.46026454, 0.0,      966.75683491,
         0.0,     1140.10761294,  538.14642887,
         0.0,     0.0,      1.0     ]

DistCoeffs: !!opencv-matrix
  rows: 5
  cols: 1
  dt: d
  data: [-0.3143816, 0.08476504, -0.0007795, 0.00021296, 0.000000]

Camera.width: 1920
Camera.height: 1080

ExtrinsicMat: !!opencv-matrix
  rows: 4
  cols: 4
  dt: d
  data: [0.00393905,-0.999663,-0.025671,0.0104296,
         0.0127264,0.0257192,-0.999588,0.251899,
         0.999911,0.00361073,0.0128234,-0.0724171,
         0,0,0,1]
